### ISSUE TITLE
运行detect.py报错

### ISSUE THREAD

**Issue by Someone1Wu** [positive666/yolov5#9]
## ❔Question
作者大大，我在训练完自己的数据集后，在detect.py里载入训练好的权重后运行，结果报错：AttributeError: 'DetectMultiBackend' object has no attribute 'fp16'，这是怎么回事呀

**Comment by positive666** [comment]
> ## ❔Question
> 作者大大，我在训练完自己的数据集后，在detect.py里载入训练好的权重后运行，结果报错：AttributeError: 'DetectMultiBackend' object has no attribute 'fp16'，这是怎么回事呀
> 
> ## Additional context

中午更新一下 是低级错误

**Comment by Someone1Wu** [comment]
> > ## ❔Question
> > 作者大大，我在训练完自己的数据集后，在detect.py里载入训练好的权重后运行，结果报错：AttributeError: 'DetectMultiBackend' object has no attribute 'fp16'，这是怎么回事呀
> > ## Additional context
> 
> 中午更新一下 是低级错误
已解决，谢谢作者大大，辛苦啦！
